-
    id: 1
    name: 'about-article läheb SAAL lehele, council ja corona INFO lehele'
    bg_color: 1a1919
    about_article:
        id: 1
    corona_article:
        id: 3
    council_article:
        id: 2
    fg_color: FFC600
